let shopItemsData = [
  {
    id: "asd",
    name: "Roti",
    price: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "sdf",
    name: "Fried Rice",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.webp",
  },
  {
    id: "dfg",
    name: "Noodles",
    price: 110,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.webp",
  },
  {
    id: "fgh",
    name: "Chicken curry",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.webp",
  },
  {
    id: "ghj",
    name: "Chicken Munchurian",
    price: 250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.webp",
  },
  {
    id: "hjk",
    name: "Paneer Masala",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.webp",
  },
  {
    id: "klp",
    name: "Veg Biriyani",
    price: 250,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.webp",
  },
  {
    id: "qwe",
    name: "Chicken Biriyani",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.webp",
  },
  {
    id: "wer",
    name: "Mutton Biriyani",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.webp",
  },
  {
    id: "rte",
    name: "Mutton Curry",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.webp",
  },
  {
    id: "tyu",
    name: "Roll",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.webp",
  },
  {
    id: "vbn",
    name: "Naan",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.webp",
  },
];
